DATASET:
  TRAIN_PATH: ""
  TEST_PATH: ""

SAM:
  CHECKPOINT: "../sam_weights/sam_vit_b_01ec64.pth"
  RANKS: 
    - 4
    - 8
    - 16
    - 64
    - 128
    - 256
    - 512
    - 1024

TRAIN:
  BATCH_SIZE: 1
  NUM_EPOCHS: 50
  GT_RATIO: 0
  CUDA: 0